repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
     - id: pyupgrade
       args: ["--py37-plus"]
  - repo: https://github.com/adamchainz/django-upgrade
    rev: '1.4.0'
    hooks:
      - id: django-upgrade
        args: [--target-version, "2.2"]
